# https://dev.azure.com/home-assistant

trigger:
  tags:
    include:
    - '*'
pr: none
variables:
  - name: versionWheels
    value: '1.3-3.7-alpine3.10'
resources:
  repositories:
    - repository: azure
      type: github
      name: 'home-assistant/ci-azure'
      endpoint: 'home-assistant'

jobs:
- template: templates/azp-job-wheels.yaml@azure
  parameters:
    builderVersion: '$(versionWheels)'
    builderApk: 'g++;gcc;file;make;musl-dev;cmake;patch;git;linux-headers;bluez-dev;libffi-dev;openssl-dev;glib-dev;eudev-dev;libxml2-dev;libxslt-dev;libpng-dev;libjpeg-turbo-dev;tiff-dev;autoconf;automake;cups-dev;gmp-dev;mpfr-dev;mpc1-dev;ffmpeg-dev'
    builderPip: 'Cython;numpy'
    builderPath: 'opencv-python'
    builderEnvFile: true
    wheelsLocal: true
    preBuild:
    - script: |
        version="$(head -n 1 requirements.txt)"
        git clone --depth 1 --shallow-submodules --recurse-submodules -b "${version##*.}" https://github.com/skvark/opencv-python

        echo "ENABLE_HEADLESS=1" > opencv-python/.env_file
        if [[ "$(buildArch)" =~ arm ]]; then
          echo 'CMAKE_ARGS="-DENABLE_NEON=OFF -DCPU_BASELINE_REQUIRE="' >> opencv-python/.env_file
        fi
      displayName: 'Setup opencv-python'
